version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"
  api:
    build: ./djangoapi
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangoapi:/app/api
    environment:
      - DEBUG=True
    ports:
      - "8001:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
volumes:
  node-modules:
