version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"
  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api
    environment:
      - DEBUG=True
    ports:
      - "8001:8000"
    depends_on:
      - db
networks:
  default:
    external:
      name: docker-compose-django-react_default
