# Generated by Django 2.1.7 on 2019-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20190307_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário'),
        ),
    ]
